---

 - hosts: server
   roles:
     - role: slurm
       slurm_type_of_node: 'front'
       slurm_wn_nodenames: ['{{ single_server_host }}']
       worker_nodes: ['{{ single_server_host }}']
     - role: slurm
       slurm_type_of_node: 'wn'
       slurm_server_name: '{{ single_server_host }}'
       worker_nodes: ['{{ single_server_host }}']

